config/routes.rb
Rails.application.routes.draw do
  # defines all the required routes related to user authentication like
  #  /users/sign_in, /users/sign_out, and /users/password/new
  devise_for :users
  get 'books/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :posts do 
    resources :comments
  end
  root "posts#index" # this is setting the homeoage '/' to 'posts' with "index" action

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/books.rb
class Books
    include HTTParty
    base_uri 'https://api.itbook.store/1.0/'

    def get_data 
        self.class.get('/new')
    end
    def list_new
        if get_data.code.to_i == 200
           get_data.parsed_response
        else
            raise "Error fetching data from the API"
        end
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
    # declare the relations
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    # declare the relations
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Books.new()
    # render @books.list_new{'books'}
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(params[:comment].permit(:name, :comment))
        redirect_to post_path(@post)
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :find_post, only: [:show, :update, :edit, :destroy]

    def index 
        @posts = Post.all.order("created_at DESC")
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)

        if @post.save
            redirect_to @post
        else
            render 'new'
        end
    end

    def show
        # @post = Post.find(params[:id])
    end

    def update
        # @post = Post.find(params[:id])
        if @post.update(post_params)
        redirect_to @post    
        else
            render 'edit'
        end
    end

    def edit
        # @post = Post.find(params[:id])
    end

    def destroy
		# @post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
	end

    
    
    private 
    
    # def get_img
    #     @options = @post.post_isbn
    #     self.class.get('/books/:isbn13', @options)
    # end
    
    def post_params
        params.require(:post).permit(:title, :content, :isbn) 
    end

    def find_post
        @post = Post.find(params[:id])
    end

end

    # post = Post.new()
    # puts post

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def get_img (isbn)
        options = @post.post_isbn
        self.class.get('/books/:isbn13', @options)
    end
end

app/views/books/index.html.erb
<% content_for :page_title, "IT-Books Index" %>

<section class="section">
<div class="container">
<% @books.list_new['books'].each do |book| %>
    <div class="card mb-4">
        <div class="class-content">
            <div class="media">
                <div class="media-content">
                    <p class="title is-4"><%= link_to book['title'], book['url'] %></p>
                </div>
            </div>
            <div class="content">
                <%= book['subtitle'] %>
            </div>
            <div class="content">
                <%= book['isbn13'] %>
            </div>
            <% if user_signed_in? %>
                <%= link_to "Create a post!", new_post_path, class:"button" %>
            <% end %>
        </div>
        <% end %>
</div>
</section>

app/views/comments/_comment.html.erb
<div class="box">
    <article class="media">
        <div class="media-content">
            <div class="content">
                <p>
                <strong><%= comment.name %>: </strong>
                <%= comment.comment %>
                </p>
            </div>
        </div>
        <%= button_to "Delete", [comment.post, comment], method: :delete, class:"button is-danger",form: {data: {turbo_confirm: 'Are you sure?'}} %>
    </article>
</div>

app/views/comments/_form.html.erb
<%# we have to pass 2 params to the simple form: %>
<%# 1. is the post to which the comment is related %>
<%# 2. build: returns one or more new objects of the collection type that have been instantiated with
 attributes and linked to this object through a foreign key 
 ATN: %>
<%= simple_form_for([@post, @post.comments.build]) do |f| %>

    <div class="field">
        <div class="control">
            
            <%= f.input :name, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'} %>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <%= f.input :comment, input_html: {class: 'textarea'}, wrapper: false, label_html: {class: 'label'} %>
        </div>
    </div>
    <%= f.button :submit, class: "button is-primary" %>


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookClub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <section class="hero is-link is-small">
  <!-- Hero head: will stick at the top -->

  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to "IT-Book Club", root_path, class: "navbar-item" %>
          <span class="navbar-burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
  <% if user_signed_in? %> 
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <%= link_to "Create new post", new_post_path, class: "navbar-item" %>
          </div>
        </div>
         <% end %>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <%= link_to "Check latest books", books_index_path, class: "navbar-item" %>
          </div>
        </div>
            <% if user_signed_in? %> 
        <div id="navbarMenuHeroA" class="navbar-item">
          <div class="navbar-end">
              <div> <%= current_user.email %> </div> 
              <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
            <% else %>
              <%= link_to "Sign in", new_user_session_path, class: "navbar-item"%> 
              <%= link_to "Sign up", new_user_registration_path, class: "navbar-item"%> 
          </div>
          </div>
              <% end %>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        <%= yield :page_title %>
      </h1>
    </div>
  </div>
</section>
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p> 
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="section">
    <%= simple_form_for @post do |f| %>
        <div class="field">
            <div class="control">
                
                <%= f.input :title, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'} %>
            </div>
        </div>

        <div class="field">
            <div class="control">
                <%= f.input :content, input_html: {class: 'textarea'}, wrapper: false, label_html: {class: 'label'} %>
            </div>
        </div>

        <div class="field">
            <div class="control">
                <%= f.input :isbn, input_html: {class: 'integer'}, wrapper: false, label_html: {class: 'label'} %>
            </div>
        </div>

        <div>
            <%= f.button :submit, class: "button is-primary" %>
        </div>

    <% end %>
</div>

app/views/posts/edit.html.erb
<% content_for :page_title, "Edit post"%>

<%= render 'form' %>

app/views/posts/index.html.erb
<% content_for :page_title, "Index" %>

<section class="section">
<div class="container">
<% @posts.each do |post| %>
    <div class="card mb-4">
        <div class="class-content">
            <div class="media">
                <div class="media-content">
                    <p class="title is-4"><%= link_to post.title, post %></p>
                </div>
            </div>
            <div class="content">
                <%= post.content %>
            </div>
        </div>
    </div>
<% end %>
</div>
</section>

app/views/posts/new.html.erb
<% content_for :page_title, "Create a new post" %>

<%= render 'form' %>

app/views/posts/show.html.erb
<% content_for :page_title, @post.title %>

<%= image_tag "https://itbook.store/img/books/#{@post.isbn}.png" if @post.isbn %>

<section class="section"> 
    <div class="container">
        <nav class="level">
            <div class="level-left">
                <p class="level-item">
                    <strong>Actions</strong>
                </p>
            </div>
<div class="level-right">
		  	<p class="level-item">
		    	<%= link_to "Edit", edit_post_path(@post), class:"button" %>
		  	</p>
		  	<p class="level-item">
				<%= button_to "Delete", post_path(@post), method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}}, class:"button is-danger" %>
				</p>
		  </div>
        </nav>
        <hr/>

        <div>
        
        </div class="content">
        <%= @post.content %>
    </div>
</section>

<section class="comments">
    <div class="container">
        <h2 class="subtitle is-5">
        <strong><%= @post.comments.count %> Comments</strong></h2>
    </div>
   <% if user_signed_in? %>
    <%= render @post.comments %>
    <div class="comment-form">
    <hr/>
    <h3 class="subtitle is-3">Leave a comment</h3>
    <%= render 'comments/form' %>
    </div>
<% end %>
</section>